// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn6iGkVQWy9P3iAckFGBnvsgsziOtFkkI',
    appId: '1:1063225074617:web:018366f7f3869d4c8dcc68',
    messagingSenderId: '1063225074617',
    projectId: 'daydream-20e85',
    authDomain: 'daydream-20e85.firebaseapp.com',
    storageBucket: 'daydream-20e85.firebasestorage.app',
    measurementId: 'G-EWCFJ24Z71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwjetNp8jKYxYCdsmrArXaSkMOTBvK9x0',
    appId: '1:1063225074617:android:06e96ce8f7f81fa58dcc68',
    messagingSenderId: '1063225074617',
    projectId: 'daydream-20e85',
    storageBucket: 'daydream-20e85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfcA66_jDO-utkmWD_o1rSkxTF2N-TtM',
    appId: '1:1063225074617:ios:bd54eea9f66648898dcc68',
    messagingSenderId: '1063225074617',
    projectId: 'daydream-20e85',
    storageBucket: 'daydream-20e85.firebasestorage.app',
    iosBundleId: 'com.example.daydream',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPfcA66_jDO-utkmWD_o1rSkxTF2N-TtM',
    appId: '1:1063225074617:ios:bd54eea9f66648898dcc68',
    messagingSenderId: '1063225074617',
    projectId: 'daydream-20e85',
    storageBucket: 'daydream-20e85.firebasestorage.app',
    iosBundleId: 'com.example.daydream',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn6iGkVQWy9P3iAckFGBnvsgsziOtFkkI',
    appId: '1:1063225074617:web:6e9872216c70e7f88dcc68',
    messagingSenderId: '1063225074617',
    projectId: 'daydream-20e85',
    authDomain: 'daydream-20e85.firebaseapp.com',
    storageBucket: 'daydream-20e85.firebasestorage.app',
    measurementId: 'G-E5DKRYQ11P',
  );
}
